import { useState } from "react";

const layers = [
  {
    id: "producers",
    label: "Layer 1 — Log Producers",
    color: "#6366f1",
    bg: "#1e1b4b",
    components: [
      { name: "Python Producer", desc: "Simulates services (auth, payment, api-gateway) writing structured logs to .log files" },
      { name: "Bash Producer", desc: "Shell script variant for lightweight simulation" },
    ],
    arrow: "writes to log files on disk ↓",
  },
  {
    id: "shipper",
    label: "Layer 2 — Log Shipper / Agent",
    color: "#f59e0b",
    bg: "#1c1400",
    components: [
      { name: "Tail & Parse", desc: "Watches log files, detects new lines (like Filebeat/Fluentd)" },
      { name: "Batch Buffer", desc: "Groups 100 events per batch; local disk buffer if API unreachable" },
      { name: "HTTP Client + Retry", desc: "Exponential backoff; posts to POST /ingest with idempotency key" },
    ],
    arrow: "HTTP POST /ingest ↓",
  },
  {
    id: "ingestion",
    label: "Layer 3 — Ingestion API (FastAPI)",
    color: "#10b981",
    bg: "#022c1e",
    components: [
      { name: "Parser & Enricher", desc: "Validates event schema, adds log_date, uuid, normalizes severity" },
      { name: "Cassandra Writer", desc: "Writes raw log events to logs_by_service_date table (high throughput)" },
      { name: "Postgres Writer", desc: "Upserts hourly aggregates to log_aggregates (error/warn/info counts)" },
      { name: "Auth Middleware", desc: "API key check on all ingest routes" },
    ],
    arrow: "writes raw logs + aggregates ↓",
  },
  {
    id: "storage",
    label: "Layer 4 — Dual Storage",
    color: "#3b82f6",
    bg: "#0c1a2e",
    components: [
      { name: "ScyllaDB / Cassandra", desc: "Raw logs — partition key (service_name, log_date) → fast time-range scans; handles 1000+ events/sec" },
      { name: "PostgreSQL", desc: "Aggregates, metadata, saved queries — relational, supports GROUP BY / rollup queries" },
    ],
    arrow: "queried by ↓",
  },
  {
    id: "query",
    label: "Layer 5 — Query API (FastAPI)",
    color: "#ec4899",
    bg: "#2d0a1e",
    components: [
      { name: "GET /logs/search", desc: "Hits Cassandra; filters by service, severity, time range, keyword; cursor-paginated" },
      { name: "GET /logs/stats", desc: "Hits Postgres log_aggregates for time-bucketed severity counts" },
      { name: "GET /services", desc: "Returns distinct services + last seen timestamp from Postgres" },
    ],
    arrow: "consumed by ↓",
  },
  {
    id: "clients",
    label: "Layer 6 — Clients",
    color: "#a78bfa",
    bg: "#1a0a2e",
    components: [
      { name: "Python CLI (Typer)", desc: "logs_cli.py — search logs, show stats, filter by time/service from terminal" },
      { name: "HTTP / curl", desc: "Direct API access; OpenAPI docs auto-generated by FastAPI at /docs" },
      { name: "(Optional) Dashboard", desc: "Simple React or Streamlit UI for log exploration" },
    ],
    arrow: null,
  },
];

const decisions = [
  { aspect: "Why Cassandra for raw logs?", reason: "Partition key (service_name, log_date) ensures all logs for a service+day are co-located → O(1) partition scans, no full table reads." },
  { aspect: "Why PostgreSQL for aggregates?", reason: "Hourly rollups need GROUP BY and SUM — Cassandra is bad at this. Postgres handles it naturally and powers the stats endpoint cheaply." },
  { aspect: "Why separate Ingestion and Query APIs?", reason: "Independent scaling. Ingestion under high write load doesn't compete with query service under heavy read load. Mirrors real-world ELK/Splunk separation." },
  { aspect: "Why local disk buffering in shipper?", reason: "If ingestion API goes down, logs shouldn't be lost. Shipper writes to a local queue file and replays on reconnect — mimics Filebeat's registry." },
  { aspect: "Why batch 100 events per request?", reason: "Reduces HTTP overhead, amortizes Cassandra write latency, and keeps ingestion API request count manageable at scale." },
];

export default function App() {
  const [active, setActive] = useState(null);

  return (
    <div style={{ background: "#0f0f0f", minHeight: "100vh", fontFamily: "monospace", padding: "24px", color: "#e5e7eb" }}>
      <h1 style={{ color: "#f9fafb", fontSize: "20px", marginBottom: "4px" }}>Distributed Log Analytics System</h1>
      <p style={{ color: "#6b7280", fontSize: "13px", marginBottom: "24px" }}>Click any layer to expand · Architecture deep-dive</p>

      {/* Architecture Stack */}
      <div style={{ display: "flex", flexDirection: "column", gap: "6px", marginBottom: "32px" }}>
        {layers.map((layer, i) => (
          <div key={layer.id}>
            <div
              onClick={() => setActive(active === layer.id ? null : layer.id)}
              style={{
                background: active === layer.id ? layer.bg : "#1a1a1a",
                border: `1.5px solid ${active === layer.id ? layer.color : "#2a2a2a"}`,
                borderRadius: "8px",
                padding: "12px 16px",
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                transition: "all 0.15s",
              }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                <div style={{ width: "10px", height: "10px", borderRadius: "50%", background: layer.color, flexShrink: 0 }} />
                <span style={{ color: layer.color, fontSize: "13px", fontWeight: "bold" }}>{layer.label}</span>
              </div>
              <div style={{ display: "flex", gap: "8px" }}>
                {layer.components.map(c => (
                  <span key={c.name} style={{ fontSize: "11px", color: "#9ca3af", background: "#222", padding: "2px 8px", borderRadius: "4px" }}>{c.name}</span>
                ))}
              </div>
            </div>

            {active === layer.id && (
              <div style={{ background: layer.bg, border: `1px solid ${layer.color}33`, borderTop: "none", borderRadius: "0 0 8px 8px", padding: "16px 20px", display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))", gap: "12px" }}>
                {layer.components.map(c => (
                  <div key={c.name} style={{ background: "#00000040", border: `1px solid ${layer.color}44`, borderRadius: "6px", padding: "10px 12px" }}>
                    <div style={{ color: layer.color, fontSize: "12px", fontWeight: "bold", marginBottom: "4px" }}>{c.name}</div>
                    <div style={{ color: "#9ca3af", fontSize: "11px", lineHeight: "1.5" }}>{c.desc}</div>
                  </div>
                ))}
              </div>
            )}

            {layer.arrow && (
              <div style={{ textAlign: "center", color: "#4b5563", fontSize: "11px", padding: "3px 0" }}>{layer.arrow}</div>
            )}
          </div>
        ))}
      </div>

      {/* Design Decisions */}
      <h2 style={{ color: "#f9fafb", fontSize: "15px", marginBottom: "12px" }}>⚡ Key Design Decisions</h2>
      <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
        {decisions.map(d => (
          <div key={d.aspect} style={{ background: "#1a1a1a", border: "1px solid #2a2a2a", borderRadius: "6px", padding: "10px 14px", display: "flex", gap: "12px" }}>
            <span style={{ color: "#f59e0b", fontSize: "12px", fontWeight: "bold", minWidth: "220px" }}>{d.aspect}</span>
            <span style={{ color: "#9ca3af", fontSize: "12px", lineHeight: "1.5" }}>{d.reason}</span>
          </div>
        ))}
      </div>

      <div style={{ marginTop: "28px", background: "#0a1a0a", border: "1px solid #14532d", borderRadius: "8px", padding: "14px 18px" }}>
        <div style={{ color: "#86efac", fontSize: "12px", fontWeight: "bold", marginBottom: "6px" }}>📋 Resume Blurb</div>
        <div style={{ color: "#a7f3d0", fontSize: "12px", lineHeight: "1.7" }}>
          Engineered a production-style Distributed Log Analytics Platform inspired by Splunk and ELK Stack — ingesting multi-service logs via local shipper agents (exponential backoff, disk buffering), storing raw events in ScyllaDB/Cassandra partitioned by service+date for high-throughput writes, and persisting hourly aggregates in PostgreSQL. Exposed REST APIs via FastAPI for log search, time-bucketed stats, and service discovery; built a Python CLI for developer access. Fully containerized with Docker Compose and deployable to free cloud tiers (Render + ScyllaDB Cloud + Railway Postgres).
        </div>
      </div>
    </div>
  );
}